package com.ken.myapplication.api

import com.ken.myapplication.data.User
import javax.inject.Inject

class LeetyApiRepositoryImpli @Inject constructor(val api: LeetyApi) : LeetyApiRepository {

    override suspend fun getUser(username : String) : User? {
        val query = getQueryString(username)
        val response = api.getUser(query)
        return response.body()?.data?.matchedUser
    }

    private fun getQueryString(username : String) : String{
        return """
            {
                matchedUser(username : "$username" ){
                    username
                    firstName
                    lastName
                    isActive
                    isCurrentUserPremium
                    isCurrentUserVerified
                    profile{
                        userSlug%20
                        realName%20
                        birthday%20
                        aboutMe%20
                        occupation%20
                        lastModified%20
                        countryName%20
                        countryCode%20
                        userAvatar%20
                        location%20
                        gender%20
                        privacyContact%20
                        websites%20
                        rewardStats%20
                        skillTags%20
                        age%20
                        education%20
                        school%20
                        company%20
                        jobTitle%20
                        yearsOfExperience%20
                        ranking%20
                        globalRanking%20
                        contestCount%20
                        acStats{
                            acQuestionCount%20
                            acSubmissionCount%20
                            totalSubmissionCount%20
                            acRate%20
                        }%20
                        starRating%20
                        publicBadgeType%20
                        postViewCount%20
                        postViewCountDiff%20
                        solutionCount%20
                        solutionCountDiff%20
                        categoryDiscussCount%20
                        categoryDiscussCountDiff%20
                        reputation%20
                        reputationDiff%20
                    }
                    socialAccounts
                    email
                    emails{
                        email%20
                        verified%20
                        primary%20
                    }
                    phone
                    isDiscussAdmin
                    isDiscussStaff
                    submitStats{
                        acSubmissionNum{
                            difficulty%20
                            submissions%20
                            count%20
                        }%20
                        totalSubmissionNum{
                            difficulty%20
                            submissions%20
                            count%20
                        }%20
                    }
                    submitStatsGlobal{
                        acSubmissionNum{
                            difficulty%20
                            submissions%20
                            count%20
                        }%20
                        totalSubmissionNum{
                            difficulty%20
                            submissions%20
                            count%20
                        }%20
                    }
                    problemsSolvedBeatsStats{
                        difficulty%20
                        percentage%20
                    }
                    contributions{
                        points%20
                        questionCount%20
                        testcaseCount%20
                    }
                    activeBadge{
                        id%20
                        creationDate%20
                        updationDate%20
                        badge%20
                        expiredDate%20
                        name%20
                        icon%20
                        shortName%20
                        displayName%20
                        expired%20
                        userCount%20
                        category%20
                        hoverText%20
                    }
                    contestBadge{
                        id%20
                        creationDate%20
                        updationDate%20
                        badge%20
                        expiredDate%20
                        name%20
                        icon%20
                        shortName%20
                        displayName%20
                        expired%20
                        userCount%20
                        category%20
                        hoverText%20
                    }
                    badges{
                        id%20
                        creationDate%20
                        updationDate%20
                        badge%20
                        expiredDate%20
                        name%20
                        icon%20
                        shortName%20
                        displayName%20
                        expired%20
                        userCount%20
                        category%20
                        hoverText%20
                    }
                    upcomingBadges{
                        name%20
                        icon%20
                        progress%20
                    }
                    nameColor
                    id
                    userCalendar{
                        activeYears%20
                        submissionCalendar%20
                        streak%20
                        totalActiveDays%20
                        dccBadges{
                            timestamp%20
                            badge{
                                id%20
                                creationDate%20
                                updationDate%20
                                badge%20
                                expiredDate%20
                                name%20
                                icon%20
                                shortName%20
                                displayName%20
                                expired%20
                                userCount%20
                                category%20
                                hoverText%20
                            }%20
                        }%20
                    }
                    yearJoined
                    joinedTimestamp
                    languageProblemCount{
                        languageName%20
                        problemsSolved%20
                    }
                    tagProblemCounts{
                        advanced{
                            tagName%20
                            problemsSolved%20
                            tagSlug%20
                        }%20
                        intermediate{
                            tagName%20
                            problemsSolved%20
                            tagSlug%20
                        }%20
                        fundamental{
                            tagName%20
                            problemsSolved%20
                            tagSlug%20
                        }%20
                    }
                    githubUrl
                    linkedinUrl
                    twitterUrl
                }
            }
        """.trimIndent()
    }
}